/**
 * @fileoverview Core type definitions for VibeCRM schema generation.
 * 
 * Reasoning:
 * - Strict TypeScript types ensure type safety across the application
 * - Matches PostgreSQL/Supabase type system
 * - Enables AI to generate valid database schemas
 * 
 * Dependencies:
 * - None (pure TypeScript types)
 */

/**
 * Allowed PostgreSQL column types
 * Limited to prevent complex/unsupported types
 */
export type PostgresType =
    | "UUID"
    | "TEXT"
    | "VARCHAR"
    | "INTEGER"
    | "BIGINT"
    | "BOOLEAN"
    | "TIMESTAMP"
    | "TIMESTAMPTZ"
    | "DATE"
    | "NUMERIC"
    | "JSONB"
    | "TEXT[]"
    | "INTEGER[]"
    | "UUID[]";

/**
 * Foreign key cascade actions
 */
export type CascadeAction = "CASCADE" | "RESTRICT" | "SET NULL" | "NO ACTION";

/**
 * Column definition in generated schema
 */
export interface ColumnDefinition {
    name: string;
    type: PostgresType;
    nullable: boolean;
    default?: string;
    unique?: boolean;
    primaryKey?: boolean;
    references?: {
        table: string;
        column: string;
        onDelete: CascadeAction;
    };
}

/**
 * Index definition for performance optimization
 */
export interface IndexDefinition {
    name: string;
    columns: string[];
    unique?: boolean;
}

/**
 * UI hints for dynamic table renderer
 */
export interface UIHints {
    icon: string; // Lucide icon name
    label: string;
    description: string;
    color?: string;
    columns: Record<
        string,
        {
            display_name: string;
            filterable?: boolean;
            sortable?: boolean;
            mobile_priority?: number; // 1 = show on mobile, 4 = hide on mobile
            type?: "currency" | "url" | "email" | "phone" | "textarea" | "enum";
        }
    >;
}

/**
 * Table definition in generated schema
 */
export interface TableDefinition {
    name: string;
    columns: ColumnDefinition[];
    indexes?: IndexDefinition[];
    ui_hints: UIHints;
}

/**
 * Relationship between tables
 */
export interface Relationship {
    from_table: string;
    from_column: string;
    to_table: string;
    to_column: string;
    type: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
}

/**
 * Complete CRM schema generated by AI
 */
export interface CRMSchema {
    version: string; // Semver (e.g., "1.0.0")
    tables: TableDefinition[];
    relationships: Relationship[];
}

/**
 * Decision trace entry for AI transparency
 */
export interface DecisionTrace {
    id: string;
    project_id: string;
    user_id: string;
    intent: string; // User's original prompt
    action: string; // What was generated/modified
    precedent: string; // AI's reasoning
    version: string; // Schema version
    timestamp: string;
    schema_before?: CRMSchema | null;
    schema_after: CRMSchema;
}

/**
 * Project entity
 */
export interface Project {
    id: string;
    user_id: string;
    name: string;
    description?: string;
    created_at: string;
    updated_at: string;
}

/**
 * Vibe config entity (stores AI-generated schemas)
 */
export interface VibeConfig {
    id: string;
    project_id: string;
    user_id: string;
    schema_version: string;
    schema_json: CRMSchema;
    is_active: boolean;
    created_at: string;
}

/**
 * Validation result type
 */
export interface ValidationResult {
    passed: boolean;
    errors?: string[];
}

/**
 * Intent classification types
 */
export type Intent = "CREATE" | "MODIFY" | "RELATE" | "DELETE_ALL" | "EXPORT" | "ADMIN" | "UNRELATED";

/**
 * User tier types
 */
export type UserTier = "free" | "pro" | "enterprise";

/**
 * Tier limits configuration
 */
export interface TierLimits {
    maxProjects: number;
    maxTables: number;
    maxColumns: number;
    maxAIRequests: number;
}
