/**
 * Agency CRM Template
 * For creative agencies managing clients, projects, and invoices
 */

import type { TemplateConfig } from '@/types/crm-config';

export const agencyTemplate: TemplateConfig = {
    id: 'agency',
    name: 'Agency CRM',
    slug: 'agency',
    industry: 'Agency',
    description: 'Manage clients, projects, and billing for creative agencies',
    icon: 'Briefcase',
    featured: true,
    useCases: [
        'Track client accounts',
        'Manage project workflows',
        'Invoice and payment tracking',
        'Team workload management',
    ],

    entities: {
        clients: {
            name: 'Client',
            namePlural: 'Clients',
            slug: 'clients',
            icon: 'Building2',
            description: 'Client companies and contacts',
            primaryField: 'company_name',
            color: '#3B82F6',

            fields: [
                {
                    id: 'id',
                    name: 'id',
                    label: 'ID',
                    type: 'text',
                    postgresType: 'UUID',
                    required: true,
                    unique: true,
                    showInTable: false,
                    showInForm: false,
                },
                {
                    id: 'company_name',
                    name: 'company_name',
                    label: 'Company Name',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'contact_name',
                    name: 'contact_name',
                    label: 'Contact Name',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 1,
                },
                {
                    id: 'email',
                    name: 'email',
                    label: 'Email',
                    type: 'email',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'phone',
                    name: 'phone',
                    label: 'Phone',
                    type: 'phone',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 3,
                },
                {
                    id: 'website',
                    name: 'website',
                    label: 'Website',
                    type: 'url',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
                {
                    id: 'status',
                    name: 'status',
                    label: 'Status',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    defaultValue: 'active',
                    options: [
                        { value: 'active', label: 'Active', color: '#10B981' },
                        { value: 'onboarding', label: 'Onboarding', color: '#F59E0B' },
                        { value: 'inactive', label: 'Inactive', color: '#6B7280' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'notes',
                    name: 'notes',
                    label: 'Notes',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
            ],

            views: [
                {
                    type: 'table',
                    name: 'All Clients',
                    default: true,
                    columns: ['company_name', 'contact_name', 'email', 'phone', 'status'],
                    sortBy: 'company_name',
                    sortOrder: 'asc',
                },
            ],
        },

        projects: {
            name: 'Project',
            namePlural: 'Projects',
            slug: 'projects',
            icon: 'FolderKanban',
            description: 'Client projects and deliverables',
            primaryField: 'project_name',
            color: '#8B5CF6',

            fields: [
                {
                    id: 'id',
                    name: 'id',
                    label: 'ID',
                    type: 'text',
                    postgresType: 'UUID',
                    required: true,
                    unique: true,
                    showInTable: false,
                    showInForm: false,
                },
                {
                    id: 'project_name',
                    name: 'project_name',
                    label: 'Project Name',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'client_name',
                    name: 'client_name',
                    label: 'Client',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'status',
                    name: 'status',
                    label: 'Status',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    defaultValue: 'planning',
                    options: [
                        { value: 'planning', label: 'Planning', color: '#6B7280' },
                        { value: 'in_progress', label: 'In Progress', color: '#3B82F6' },
                        { value: 'review', label: 'Review', color: '#F59E0B' },
                        { value: 'completed', label: 'Completed', color: '#10B981' },
                        { value: 'on_hold', label: 'On Hold', color: '#EF4444' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'project_value',
                    name: 'project_value',
                    label: 'Project Value',
                    type: 'currency',
                    postgresType: 'NUMERIC',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 3,
                },
                {
                    id: 'start_date',
                    name: 'start_date',
                    label: 'Start Date',
                    type: 'date',
                    postgresType: 'DATE',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 4,
                },
                {
                    id: 'deadline',
                    name: 'deadline',
                    label: 'Deadline',
                    type: 'date',
                    postgresType: 'DATE',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 3,
                },
                {
                    id: 'description',
                    name: 'description',
                    label: 'Description',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
            ],

            views: [
                {
                    type: 'kanban',
                    name: 'Workflow',
                    default: true,
                    groupByField: 'status',
                },
                {
                    type: 'table',
                    name: 'List View',
                    columns: ['project_name', 'client_name', 'status', 'project_value', 'deadline'],
                    sortBy: 'deadline',
                    sortOrder: 'asc',
                },
            ],
        },

        invoices: {
            name: 'Invoice',
            namePlural: 'Invoices',
            slug: 'invoices',
            icon: 'FileText',
            description: 'Billing and payment tracking',
            primaryField: 'invoice_number',
            color: '#10B981',

            fields: [
                {
                    id: 'id',
                    name: 'id',
                    label: 'ID',
                    type: 'text',
                    postgresType: 'UUID',
                    required: true,
                    unique: true,
                    showInTable: false,
                    showInForm: false,
                },
                {
                    id: 'invoice_number',
                    name: 'invoice_number',
                    label: 'Invoice #',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    unique: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'client_name',
                    name: 'client_name',
                    label: 'Client',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'project_name',
                    name: 'project_name',
                    label: 'Project',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 3,
                },
                {
                    id: 'amount',
                    name: 'amount',
                    label: 'Amount',
                    type: 'currency',
                    postgresType: 'NUMERIC',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'status',
                    name: 'status',
                    label: 'Status',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    defaultValue: 'draft',
                    options: [
                        { value: 'draft', label: 'Draft', color: '#6B7280' },
                        { value: 'sent', label: 'Sent', color: '#3B82F6' },
                        { value: 'paid', label: 'Paid', color: '#10B981' },
                        { value: 'overdue', label: 'Overdue', color: '#EF4444' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'issue_date',
                    name: 'issue_date',
                    label: 'Issue Date',
                    type: 'date',
                    postgresType: 'DATE',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 4,
                },
                {
                    id: 'due_date',
                    name: 'due_date',
                    label: 'Due Date',
                    type: 'date',
                    postgresType: 'DATE',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 3,
                },
                {
                    id: 'notes',
                    name: 'notes',
                    label: 'Notes',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
            ],

            views: [
                {
                    type: 'table',
                    name: 'All Invoices',
                    default: true,
                    columns: ['invoice_number', 'client_name', 'amount', 'status', 'due_date'],
                    sortBy: 'issue_date',
                    sortOrder: 'desc',
                },
            ],
        },
    },

    dashboard: {
        widgets: [
            {
                type: 'stats',
                title: 'Active Projects',
                entityName: 'projects',
                metric: 'count',
                size: 'small',
                position: { x: 0, y: 0 },
                filters: [{ field: 'status', operator: 'in', value: ['planning', 'in_progress', 'review'] }],
            },
            {
                type: 'stats',
                title: 'Total Clients',
                entityName: 'clients',
                metric: 'count',
                size: 'small',
                position: { x: 1, y: 0 },
                filters: [{ field: 'status', operator: 'equals', value: 'active' }],
            },
            {
                type: 'stats',
                title: 'Unpaid Invoices',
                entityName: 'invoices',
                metric: 'sum',
                field: 'amount',
                size: 'small',
                position: { x: 2, y: 0 },
                filters: [{ field: 'status', operator: 'in', value: ['sent', 'overdue'] }],
            },
            {
                type: 'chart',
                title: 'Projects by Status',
                entityName: 'projects',
                chartType: 'bar',
                groupByField: 'status',
                size: 'medium',
                position: { x: 0, y: 1 },
            },
            {
                type: 'list',
                title: 'Recent Invoices',
                entityName: 'invoices',
                limit: 5,
                size: 'medium',
                position: { x: 1, y: 1 },
            },
        ],
    },
};
