/**
 * Real Estate CRM Template
 * For real estate agencies managing properties, clients, and showings
 */

import type { TemplateConfig } from '@/types/crm-config';

export const realEstateTemplate: TemplateConfig = {
    id: 'real-estate',
    name: 'Real Estate CRM',
    slug: 'real-estate',
    industry: 'Real Estate',
    description: 'Manage properties, clients, and showings with pipeline tracking',
    icon: 'Home',
    featured: true,
    useCases: [
        'Track property listings',
        'Manage buyer and seller relationships',
        'Schedule and track property showings',
        'Monitor deal pipeline from listing to closing',
    ],

    entities: {
        properties: {
            name: 'Property',
            namePlural: 'Properties',
            slug: 'properties',
            icon: 'Home',
            description: 'Real estate listings and inventory',
            primaryField: 'address',
            color: '#3B82F6',

            fields: [
                {
                    id: 'id',
                    name: 'id',
                    label: 'ID',
                    type: 'text',
                    postgresType: 'UUID',
                    required: true,
                    unique: true,
                    showInTable: false,
                    showInForm: false,
                },
                {
                    id: 'address',
                    name: 'address',
                    label: 'Address',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'property_type',
                    name: 'property_type',
                    label: 'Property Type',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    options: [
                        { value: 'house', label: 'House' },
                        { value: 'condo', label: 'Condo' },
                        { value: 'apartment', label: 'Apartment' },
                        { value: 'land', label: 'Land' },
                        { value: 'commercial', label: 'Commercial' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'price',
                    name: 'price',
                    label: 'Price',
                    type: 'currency',
                    postgresType: 'NUMERIC',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'status',
                    name: 'status',
                    label: 'Status',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    defaultValue: 'active',
                    options: [
                        { value: 'active', label: 'Active', color: '#10B981' },
                        { value: 'pending', label: 'Pending', color: '#F59E0B' },
                        { value: 'sold', label: 'Sold', color: '#6366F1' },
                        { value: 'withdrawn', label: 'Withdrawn', color: '#6B7280' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'bedrooms',
                    name: 'bedrooms',
                    label: 'Bedrooms',
                    type: 'number',
                    postgresType: 'INTEGER',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 3,
                },
                {
                    id: 'bathrooms',
                    name: 'bathrooms',
                    label: 'Bathrooms',
                    type: 'number',
                    postgresType: 'NUMERIC',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 3,
                },
                {
                    id: 'square_feet',
                    name: 'square_feet',
                    label: 'Square Feet',
                    type: 'number',
                    postgresType: 'INTEGER',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 4,
                },
                {
                    id: 'listing_date',
                    name: 'listing_date',
                    label: 'Listing Date',
                    type: 'date',
                    postgresType: 'DATE',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 4,
                },
                {
                    id: 'description',
                    name: 'description',
                    label: 'Description',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
            ],

            views: [
                {
                    type: 'table',
                    name: 'All Properties',
                    default: true,
                    columns: ['address', 'property_type', 'price', 'status', 'bedrooms', 'bathrooms'],
                    sortBy: 'listing_date',
                    sortOrder: 'desc',
                },
                {
                    type: 'kanban',
                    name: 'Pipeline',
                    groupByField: 'status',
                },
            ],
        },

        clients: {
            name: 'Client',
            namePlural: 'Clients',
            slug: 'clients',
            icon: 'Users',
            description: 'Buyers and sellers',
            primaryField: 'full_name',
            color: '#8B5CF6',

            fields: [
                {
                    id: 'id',
                    name: 'id',
                    label: 'ID',
                    type: 'text',
                    postgresType: 'UUID',
                    required: true,
                    unique: true,
                    showInTable: false,
                    showInForm: false,
                },
                {
                    id: 'full_name',
                    name: 'full_name',
                    label: 'Full Name',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'email',
                    name: 'email',
                    label: 'Email',
                    type: 'email',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'phone',
                    name: 'phone',
                    label: 'Phone',
                    type: 'phone',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 2,
                },
                {
                    id: 'client_type',
                    name: 'client_type',
                    label: 'Client Type',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    options: [
                        { value: 'buyer', label: 'Buyer' },
                        { value: 'seller', label: 'Seller' },
                        { value: 'both', label: 'Both' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'budget',
                    name: 'budget',
                    label: 'Budget',
                    type: 'currency',
                    postgresType: 'NUMERIC',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 3,
                },
                {
                    id: 'notes',
                    name: 'notes',
                    label: 'Notes',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
            ],

            views: [
                {
                    type: 'table',
                    name: 'All Clients',
                    default: true,
                    columns: ['full_name', 'email', 'phone', 'client_type', 'budget'],
                    sortBy: 'full_name',
                    sortOrder: 'asc',
                },
            ],
        },

        showings: {
            name: 'Showing',
            namePlural: 'Showings',
            slug: 'showings',
            icon: 'Calendar',
            description: 'Property showing appointments',
            primaryField: 'title',
            color: '#EC4899',

            fields: [
                {
                    id: 'id',
                    name: 'id',
                    label: 'ID',
                    type: 'text',
                    postgresType: 'UUID',
                    required: true,
                    unique: true,
                    showInTable: false,
                    showInForm: false,
                },
                {
                    id: 'title',
                    name: 'title',
                    label: 'Title',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 1,
                },
                {
                    id: 'showing_date',
                    name: 'showing_date',
                    label: 'Date & Time',
                    type: 'datetime',
                    postgresType: 'TIMESTAMPTZ',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'property_address',
                    name: 'property_address',
                    label: 'Property',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 2,
                },
                {
                    id: 'client_name',
                    name: 'client_name',
                    label: 'Client',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 2,
                },
                {
                    id: 'status',
                    name: 'status',
                    label: 'Status',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    defaultValue: 'scheduled',
                    options: [
                        { value: 'scheduled', label: 'Scheduled', color: '#3B82F6' },
                        { value: 'completed', label: 'Completed', color: '#10B981' },
                        { value: 'cancelled', label: 'Cancelled', color: '#EF4444' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 3,
                },
                {
                    id: 'notes',
                    name: 'notes',
                    label: 'Notes',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
            ],

            views: [
                {
                    type: 'calendar',
                    name: 'Calendar',
                    default: true,
                    dateField: 'showing_date',
                    titleField: 'title',
                },
                {
                    type: 'table',
                    name: 'List View',
                    columns: ['title', 'showing_date', 'property_address', 'client_name', 'status'],
                    sortBy: 'showing_date',
                    sortOrder: 'asc',
                },
            ],
        },
    },

    dashboard: {
        widgets: [
            {
                type: 'stats',
                title: 'Active Listings',
                entityName: 'properties',
                metric: 'count',
                size: 'small',
                position: { x: 0, y: 0 },
                filters: [{ field: 'status', operator: 'equals', value: 'active' }],
            },
            {
                type: 'stats',
                title: 'Total Clients',
                entityName: 'clients',
                metric: 'count',
                size: 'small',
                position: { x: 1, y: 0 },
            },
            {
                type: 'stats',
                title: 'Upcoming Showings',
                entityName: 'showings',
                metric: 'count',
                size: 'small',
                position: { x: 2, y: 0 },
                filters: [{ field: 'status', operator: 'equals', value: 'scheduled' }],
            },
            {
                type: 'chart',
                title: 'Properties by Status',
                entityName: 'properties',
                chartType: 'pie',
                groupByField: 'status',
                size: 'medium',
                position: { x: 0, y: 1 },
            },
            {
                type: 'list',
                title: 'Recent Showings',
                entityName: 'showings',
                limit: 5,
                size: 'medium',
                position: { x: 1, y: 1 },
            },
        ],
    },
};
