/**
 * Retail CRM Template
 * For retail stores managing customers, products, and orders
 */

import type { TemplateConfig } from '@/types/crm-config';

export const retailTemplate: TemplateConfig = {
    id: 'retail',
    name: 'Retail CRM',
    slug: 'retail',
    industry: 'Retail',
    description: 'Manage customers, products, and orders for retail businesses',
    icon: 'ShoppingBag',
    featured: true,
    useCases: [
        'Track customer purchase history',
        'Manage product inventory',
        'Process and fulfill orders',
        'Monitor sales performance',
    ],

    entities: {
        customers: {
            name: 'Customer',
            namePlural: 'Customers',
            slug: 'customers',
            icon: 'User',
            description: 'Customer database and contact info',
            primaryField: 'full_name',
            color: '#3B82F6',

            fields: [
                {
                    id: 'id',
                    name: 'id',
                    label: 'ID',
                    type: 'text',
                    postgresType: 'UUID',
                    required: true,
                    unique: true,
                    showInTable: false,
                    showInForm: false,
                },
                {
                    id: 'full_name',
                    name: 'full_name',
                    label: 'Full Name',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'email',
                    name: 'email',
                    label: 'Email',
                    type: 'email',
                    postgresType: 'TEXT',
                    required: true,
                    unique: true,
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'phone',
                    name: 'phone',
                    label: 'Phone',
                    type: 'phone',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 2,
                },
                {
                    id: 'customer_type',
                    name: 'customer_type',
                    label: 'Customer Type',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    defaultValue: 'regular',
                    options: [
                        { value: 'regular', label: 'Regular' },
                        { value: 'vip', label: 'VIP', color: '#F59E0B' },
                        { value: 'wholesale', label: 'Wholesale', color: '#8B5CF6' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'total_spent',
                    name: 'total_spent',
                    label: 'Total Spent',
                    type: 'currency',
                    postgresType: 'NUMERIC',
                    required: false,
                    defaultValue: '0',
                    showInTable: true,
                    showInForm: false,
                    sortable: true,
                    mobilePriority: 3,
                },
                {
                    id: 'address',
                    name: 'address',
                    label: 'Address',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
                {
                    id: 'notes',
                    name: 'notes',
                    label: 'Notes',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
            ],

            views: [
                {
                    type: 'table',
                    name: 'All Customers',
                    default: true,
                    columns: ['full_name', 'email', 'phone', 'customer_type', 'total_spent'],
                    sortBy: 'total_spent',
                    sortOrder: 'desc',
                },
            ],
        },

        products: {
            name: 'Product',
            namePlural: 'Products',
            slug: 'products',
            icon: 'Package',
            description: 'Product catalog and inventory',
            primaryField: 'product_name',
            color: '#8B5CF6',

            fields: [
                {
                    id: 'id',
                    name: 'id',
                    label: 'ID',
                    type: 'text',
                    postgresType: 'UUID',
                    required: true,
                    unique: true,
                    showInTable: false,
                    showInForm: false,
                },
                {
                    id: 'product_name',
                    name: 'product_name',
                    label: 'Product Name',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'sku',
                    name: 'sku',
                    label: 'SKU',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    unique: true,
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'category',
                    name: 'category',
                    label: 'Category',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    options: [
                        { value: 'electronics', label: 'Electronics' },
                        { value: 'clothing', label: 'Clothing' },
                        { value: 'home', label: 'Home & Garden' },
                        { value: 'sports', label: 'Sports' },
                        { value: 'other', label: 'Other' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 3,
                },
                {
                    id: 'price',
                    name: 'price',
                    label: 'Price',
                    type: 'currency',
                    postgresType: 'NUMERIC',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'stock_quantity',
                    name: 'stock_quantity',
                    label: 'Stock Quantity',
                    type: 'number',
                    postgresType: 'INTEGER',
                    required: true,
                    defaultValue: '0',
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'status',
                    name: 'status',
                    label: 'Status',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    defaultValue: 'active',
                    options: [
                        { value: 'active', label: 'Active', color: '#10B981' },
                        { value: 'low_stock', label: 'Low Stock', color: '#F59E0B' },
                        { value: 'out_of_stock', label: 'Out of Stock', color: '#EF4444' },
                        { value: 'discontinued', label: 'Discontinued', color: '#6B7280' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'description',
                    name: 'description',
                    label: 'Description',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
            ],

            views: [
                {
                    type: 'table',
                    name: 'All Products',
                    default: true,
                    columns: ['product_name', 'sku', 'category', 'price', 'stock_quantity', 'status'],
                    sortBy: 'product_name',
                    sortOrder: 'asc',
                },
                {
                    type: 'grid',
                    name: 'Grid View',
                },
            ],
        },

        orders: {
            name: 'Order',
            namePlural: 'Orders',
            slug: 'orders',
            icon: 'ShoppingCart',
            description: 'Customer orders and fulfillment',
            primaryField: 'order_number',
            color: '#10B981',

            fields: [
                {
                    id: 'id',
                    name: 'id',
                    label: 'ID',
                    type: 'text',
                    postgresType: 'UUID',
                    required: true,
                    unique: true,
                    showInTable: false,
                    showInForm: false,
                },
                {
                    id: 'order_number',
                    name: 'order_number',
                    label: 'Order #',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    unique: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'customer_name',
                    name: 'customer_name',
                    label: 'Customer',
                    type: 'text',
                    postgresType: 'TEXT',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'order_date',
                    name: 'order_date',
                    label: 'Order Date',
                    type: 'date',
                    postgresType: 'DATE',
                    required: true,
                    defaultValue: 'NOW()',
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 3,
                },
                {
                    id: 'total_amount',
                    name: 'total_amount',
                    label: 'Total',
                    type: 'currency',
                    postgresType: 'NUMERIC',
                    required: true,
                    showInTable: true,
                    showInForm: true,
                    sortable: true,
                    mobilePriority: 1,
                },
                {
                    id: 'status',
                    name: 'status',
                    label: 'Status',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    defaultValue: 'pending',
                    options: [
                        { value: 'pending', label: 'Pending', color: '#6B7280' },
                        { value: 'processing', label: 'Processing', color: '#3B82F6' },
                        { value: 'shipped', label: 'Shipped', color: '#F59E0B' },
                        { value: 'delivered', label: 'Delivered', color: '#10B981' },
                        { value: 'cancelled', label: 'Cancelled', color: '#EF4444' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    filterable: true,
                    mobilePriority: 2,
                },
                {
                    id: 'payment_method',
                    name: 'payment_method',
                    label: 'Payment Method',
                    type: 'select',
                    postgresType: 'TEXT',
                    required: true,
                    options: [
                        { value: 'cash', label: 'Cash' },
                        { value: 'card', label: 'Credit/Debit Card' },
                        { value: 'online', label: 'Online Payment' },
                    ],
                    showInTable: true,
                    showInForm: true,
                    mobilePriority: 4,
                },
                {
                    id: 'notes',
                    name: 'notes',
                    label: 'Notes',
                    type: 'textarea',
                    postgresType: 'TEXT',
                    required: false,
                    showInTable: false,
                    showInForm: true,
                },
            ],

            views: [
                {
                    type: 'table',
                    name: 'All Orders',
                    default: true,
                    columns: ['order_number', 'customer_name', 'order_date', 'total_amount', 'status'],
                    sortBy: 'order_date',
                    sortOrder: 'desc',
                },
                {
                    type: 'kanban',
                    name: 'Fulfillment Pipeline',
                    groupByField: 'status',
                },
            ],
        },
    },

    dashboard: {
        widgets: [
            {
                type: 'stats',
                title: 'Total Customers',
                entityName: 'customers',
                metric: 'count',
                size: 'small',
                position: { x: 0, y: 0 },
            },
            {
                type: 'stats',
                title: 'Products in Stock',
                entityName: 'products',
                metric: 'count',
                size: 'small',
                position: { x: 1, y: 0 },
                filters: [{ field: 'status', operator: 'equals', value: 'active' }],
            },
            {
                type: 'stats',
                title: 'Pending Orders',
                entityName: 'orders',
                metric: 'count',
                size: 'small',
                position: { x: 2, y: 0 },
                filters: [{ field: 'status', operator: 'in', value: ['pending', 'processing'] }],
            },
            {
                type: 'chart',
                title: 'Orders by Status',
                entityName: 'orders',
                chartType: 'pie',
                groupByField: 'status',
                size: 'medium',
                position: { x: 0, y: 1 },
            },
            {
                type: 'list',
                title: 'Recent Orders',
                entityName: 'orders',
                limit: 5,
                size: 'medium',
                position: { x: 1, y: 1 },
            },
        ],
    },
};
